CREATE TABLE brands (
                        id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR2(50) NOT NULL,
                        CONSTRAINT uk_brands_name UNIQUE (name)
);