CREATE TABLE models (
                        id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name     VARCHAR2(50) NOT NULL,
                        brand_id NUMBER(10) NOT NULL,
                        CONSTRAINT fk_models_brand FOREIGN KEY (brand_id) REFERENCES brands (id)
);
CREATE INDEX idx_models_brand_id ON models (brand_id);