CREATE TABLE cars (
                      id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      plate        VARCHAR2(20) NOT NULL,
                      daily_price  NUMBER(10,2) NOT NULL,
                      model_year   NUMBER(4) NOT NULL,
                      state        VARCHAR2(20) NOT NULL,
                      model_id     NUMBER(10) NOT NULL,
                      CONSTRAINT uk_cars_plate UNIQUE (plate),
                      CONSTRAINT fk_cars_model FOREIGN KEY (model_id) REFERENCES models (id)
);

CREATE INDEX idx_cars_model_id ON cars (model_id);