CREATE TABLE users (
                       id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email    VARCHAR2(100) NOT NULL,
                       password VARCHAR2(100) NOT NULL,
                       role     VARCHAR2(20) NOT NULL,
                       CONSTRAINT uk_users_email UNIQUE (email)
);