CREATE TABLE accounts (
                          id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          account_number  VARCHAR2(34) NOT NULL,
                          owner_name      VARCHAR2(255) NOT NULL,
                          balance         NUMBER(19,4) NOT NULL,
                          currency        VARCHAR2(3) NOT NULL,
                          created_at      TIMESTAMP(6) WITH TIME ZONE,
                          updated_at      TIMESTAMP(6) WITH TIME ZONE,
                          created_by      VARCHAR2(100),
                          updated_by      VARCHAR2(100),
                          CONSTRAINT uk_accounts_account_number UNIQUE (account_number)
);