CREATE TABLE transfer_transactions (
                                       id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       reference         VARCHAR2(36) NOT NULL,
                                       from_account_id   NUMBER(19) NOT NULL,
                                       to_account_id     NUMBER(19) NOT NULL,
                                       amount            NUMBER(19,4) NOT NULL,
                                       currency          VARCHAR2(3) NOT NULL,
                                       status            VARCHAR2(20) NOT NULL,
                                       description       VARCHAR2(255),
                                       created_at        TIMESTAMP(6) WITH TIME ZONE,
                                       updated_at        TIMESTAMP(6) WITH TIME ZONE,
                                       created_by        VARCHAR2(100),
                                       updated_by        VARCHAR2(100),
                                       CONSTRAINT uk_transfer_transactions_reference UNIQUE (reference),
                                       CONSTRAINT fk_transfer_from_account FOREIGN KEY (from_account_id) REFERENCES accounts(id),
                                       CONSTRAINT fk_transfer_to_account   FOREIGN KEY (to_account_id) REFERENCES accounts(id),
                                       CONSTRAINT chk_transfer_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_transfer_from_account ON transfer_transactions(from_account_id);
CREATE INDEX idx_transfer_to_account   ON transfer_transactions(to_account_id);